//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\dev\xcss-parser-csharp\XcssSelectors\Antlr\Xcss\AntlrXcssParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAntlrXcssParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AntlrXcssParserBaseListener : IAntlrXcssParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] AntlrXcssParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] AntlrXcssParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.selectorGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectorGroup([NotNull] AntlrXcssParser.SelectorGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.selectorGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectorGroup([NotNull] AntlrXcssParser.SelectorGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] AntlrXcssParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] AntlrXcssParser.SelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.combinator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCombinator([NotNull] AntlrXcssParser.CombinatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.combinator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCombinator([NotNull] AntlrXcssParser.CombinatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.simpleSelectorSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleSelectorSequence([NotNull] AntlrXcssParser.SimpleSelectorSequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.simpleSelectorSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleSelectorSequence([NotNull] AntlrXcssParser.SimpleSelectorSequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementId([NotNull] AntlrXcssParser.ElementIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementId([NotNull] AntlrXcssParser.ElementIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementIdValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementIdValue([NotNull] AntlrXcssParser.ElementIdValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementIdValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementIdValue([NotNull] AntlrXcssParser.ElementIdValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.tagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTagName([NotNull] AntlrXcssParser.TagNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.tagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTagName([NotNull] AntlrXcssParser.TagNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.typeSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSelector([NotNull] AntlrXcssParser.TypeSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.typeSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSelector([NotNull] AntlrXcssParser.TypeSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.typeNamespacePrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNamespacePrefix([NotNull] AntlrXcssParser.TypeNamespacePrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.typeNamespacePrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNamespacePrefix([NotNull] AntlrXcssParser.TypeNamespacePrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementName([NotNull] AntlrXcssParser.ElementNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementName([NotNull] AntlrXcssParser.ElementNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.universal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniversal([NotNull] AntlrXcssParser.UniversalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.universal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniversal([NotNull] AntlrXcssParser.UniversalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassName([NotNull] AntlrXcssParser.ClassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassName([NotNull] AntlrXcssParser.ClassNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.classNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassNameValue([NotNull] AntlrXcssParser.ClassNameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.classNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassNameValue([NotNull] AntlrXcssParser.ClassNameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] AntlrXcssParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] AntlrXcssParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.xpathCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXpathCondition([NotNull] AntlrXcssParser.XpathConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.xpathCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXpathCondition([NotNull] AntlrXcssParser.XpathConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementIndex([NotNull] AntlrXcssParser.ElementIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementIndex([NotNull] AntlrXcssParser.ElementIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.subelementSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubelementSelector([NotNull] AntlrXcssParser.SubelementSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.subelementSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubelementSelector([NotNull] AntlrXcssParser.SubelementSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] AntlrXcssParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] AntlrXcssParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.textValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextValue([NotNull] AntlrXcssParser.TextValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.textValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextValue([NotNull] AntlrXcssParser.TextValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.textMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextMatchStyle([NotNull] AntlrXcssParser.TextMatchStyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.textMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextMatchStyle([NotNull] AntlrXcssParser.TextMatchStyleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrib([NotNull] AntlrXcssParser.AttribContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrib([NotNull] AntlrXcssParser.AttribContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attribName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribName([NotNull] AntlrXcssParser.AttribNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attribName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribName([NotNull] AntlrXcssParser.AttribNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attribMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribMatchStyle([NotNull] AntlrXcssParser.AttribMatchStyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attribMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribMatchStyle([NotNull] AntlrXcssParser.AttribMatchStyleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attribValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribValue([NotNull] AntlrXcssParser.AttribValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attribValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribValue([NotNull] AntlrXcssParser.AttribValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.pseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPseudo([NotNull] AntlrXcssParser.PseudoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.pseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPseudo([NotNull] AntlrXcssParser.PseudoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.functionalPseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionalPseudo([NotNull] AntlrXcssParser.FunctionalPseudoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.functionalPseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionalPseudo([NotNull] AntlrXcssParser.FunctionalPseudoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] AntlrXcssParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] AntlrXcssParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegation([NotNull] AntlrXcssParser.NegationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegation([NotNull] AntlrXcssParser.NegationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.negationArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegationArg([NotNull] AntlrXcssParser.NegationArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.negationArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegationArg([NotNull] AntlrXcssParser.NegationArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdent([NotNull] AntlrXcssParser.IdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdent([NotNull] AntlrXcssParser.IdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.ws"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWs([NotNull] AntlrXcssParser.WsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.ws"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWs([NotNull] AntlrXcssParser.WsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
