//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\dev\xcss-parser-csharp\XcssSelectors\Antlr\Xcss\AntlrXcssParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AntlrXcssParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAntlrXcssParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] AntlrXcssParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] AntlrXcssParser.ParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.selectorGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectorGroup([NotNull] AntlrXcssParser.SelectorGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.selectorGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectorGroup([NotNull] AntlrXcssParser.SelectorGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] AntlrXcssParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] AntlrXcssParser.SelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.combinator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCombinator([NotNull] AntlrXcssParser.CombinatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.combinator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCombinator([NotNull] AntlrXcssParser.CombinatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.simpleSelectorSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleSelectorSequence([NotNull] AntlrXcssParser.SimpleSelectorSequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.simpleSelectorSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleSelectorSequence([NotNull] AntlrXcssParser.SimpleSelectorSequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementId([NotNull] AntlrXcssParser.ElementIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementId([NotNull] AntlrXcssParser.ElementIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementIdValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementIdValue([NotNull] AntlrXcssParser.ElementIdValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementIdValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementIdValue([NotNull] AntlrXcssParser.ElementIdValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.tagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTagName([NotNull] AntlrXcssParser.TagNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.tagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTagName([NotNull] AntlrXcssParser.TagNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.typeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSelector([NotNull] AntlrXcssParser.TypeSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.typeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSelector([NotNull] AntlrXcssParser.TypeSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.typeNamespacePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNamespacePrefix([NotNull] AntlrXcssParser.TypeNamespacePrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.typeNamespacePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNamespacePrefix([NotNull] AntlrXcssParser.TypeNamespacePrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementName([NotNull] AntlrXcssParser.ElementNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementName([NotNull] AntlrXcssParser.ElementNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.universal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUniversal([NotNull] AntlrXcssParser.UniversalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.universal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUniversal([NotNull] AntlrXcssParser.UniversalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] AntlrXcssParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] AntlrXcssParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.classNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassNameValue([NotNull] AntlrXcssParser.ClassNameValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.classNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassNameValue([NotNull] AntlrXcssParser.ClassNameValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] AntlrXcssParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] AntlrXcssParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.xpathCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXpathCondition([NotNull] AntlrXcssParser.XpathConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.xpathCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXpathCondition([NotNull] AntlrXcssParser.XpathConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.elementIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementIndex([NotNull] AntlrXcssParser.ElementIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.elementIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementIndex([NotNull] AntlrXcssParser.ElementIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.subelementSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubelementSelector([NotNull] AntlrXcssParser.SubelementSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.subelementSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubelementSelector([NotNull] AntlrXcssParser.SubelementSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] AntlrXcssParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] AntlrXcssParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.textValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextValue([NotNull] AntlrXcssParser.TextValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.textValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextValue([NotNull] AntlrXcssParser.TextValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.textMatchStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextMatchStyle([NotNull] AntlrXcssParser.TextMatchStyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.textMatchStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextMatchStyle([NotNull] AntlrXcssParser.TextMatchStyleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrib([NotNull] AntlrXcssParser.AttribContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrib([NotNull] AntlrXcssParser.AttribContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attribName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribName([NotNull] AntlrXcssParser.AttribNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attribName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribName([NotNull] AntlrXcssParser.AttribNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attribMatchStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribMatchStyle([NotNull] AntlrXcssParser.AttribMatchStyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attribMatchStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribMatchStyle([NotNull] AntlrXcssParser.AttribMatchStyleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.attribValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribValue([NotNull] AntlrXcssParser.AttribValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.attribValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribValue([NotNull] AntlrXcssParser.AttribValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.pseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPseudo([NotNull] AntlrXcssParser.PseudoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.pseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPseudo([NotNull] AntlrXcssParser.PseudoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.functionalPseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionalPseudo([NotNull] AntlrXcssParser.FunctionalPseudoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.functionalPseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionalPseudo([NotNull] AntlrXcssParser.FunctionalPseudoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] AntlrXcssParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] AntlrXcssParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegation([NotNull] AntlrXcssParser.NegationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegation([NotNull] AntlrXcssParser.NegationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.negationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegationArg([NotNull] AntlrXcssParser.NegationArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.negationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegationArg([NotNull] AntlrXcssParser.NegationArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdent([NotNull] AntlrXcssParser.IdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdent([NotNull] AntlrXcssParser.IdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AntlrXcssParser.ws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWs([NotNull] AntlrXcssParser.WsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AntlrXcssParser.ws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWs([NotNull] AntlrXcssParser.WsContext context);
}
