//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\dev\xcss-parser-csharp\AntlrCSharp\antlr\XCSSParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXCSSParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class XCSSParserBaseListener : IXCSSParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] XCSSParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] XCSSParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.selectorGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectorGroup([NotNull] XCSSParser.SelectorGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.selectorGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectorGroup([NotNull] XCSSParser.SelectorGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] XCSSParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] XCSSParser.SelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.combinator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCombinator([NotNull] XCSSParser.CombinatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.combinator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCombinator([NotNull] XCSSParser.CombinatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.simpleSelectorSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleSelectorSequence([NotNull] XCSSParser.SimpleSelectorSequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.simpleSelectorSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleSelectorSequence([NotNull] XCSSParser.SimpleSelectorSequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.elementId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementId([NotNull] XCSSParser.ElementIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.elementId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementId([NotNull] XCSSParser.ElementIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.elementIdValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementIdValue([NotNull] XCSSParser.ElementIdValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.elementIdValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementIdValue([NotNull] XCSSParser.ElementIdValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.tagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTagName([NotNull] XCSSParser.TagNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.tagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTagName([NotNull] XCSSParser.TagNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.typeSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSelector([NotNull] XCSSParser.TypeSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.typeSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSelector([NotNull] XCSSParser.TypeSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.typeNamespacePrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNamespacePrefix([NotNull] XCSSParser.TypeNamespacePrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.typeNamespacePrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNamespacePrefix([NotNull] XCSSParser.TypeNamespacePrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.elementName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementName([NotNull] XCSSParser.ElementNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.elementName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementName([NotNull] XCSSParser.ElementNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.universal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniversal([NotNull] XCSSParser.UniversalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.universal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniversal([NotNull] XCSSParser.UniversalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassName([NotNull] XCSSParser.ClassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassName([NotNull] XCSSParser.ClassNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.classNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassNameValue([NotNull] XCSSParser.ClassNameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.classNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassNameValue([NotNull] XCSSParser.ClassNameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] XCSSParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] XCSSParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] XCSSParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] XCSSParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.textValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextValue([NotNull] XCSSParser.TextValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.textValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextValue([NotNull] XCSSParser.TextValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.textMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextMatchStyle([NotNull] XCSSParser.TextMatchStyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.textMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextMatchStyle([NotNull] XCSSParser.TextMatchStyleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.attrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrib([NotNull] XCSSParser.AttribContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.attrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrib([NotNull] XCSSParser.AttribContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.attribName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribName([NotNull] XCSSParser.AttribNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.attribName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribName([NotNull] XCSSParser.AttribNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.attribMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribMatchStyle([NotNull] XCSSParser.AttribMatchStyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.attribMatchStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribMatchStyle([NotNull] XCSSParser.AttribMatchStyleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.attribValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribValue([NotNull] XCSSParser.AttribValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.attribValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribValue([NotNull] XCSSParser.AttribValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.pseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPseudo([NotNull] XCSSParser.PseudoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.pseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPseudo([NotNull] XCSSParser.PseudoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.functionalPseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionalPseudo([NotNull] XCSSParser.FunctionalPseudoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.functionalPseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionalPseudo([NotNull] XCSSParser.FunctionalPseudoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] XCSSParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] XCSSParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegation([NotNull] XCSSParser.NegationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegation([NotNull] XCSSParser.NegationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.negationArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegationArg([NotNull] XCSSParser.NegationArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.negationArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegationArg([NotNull] XCSSParser.NegationArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdent([NotNull] XCSSParser.IdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdent([NotNull] XCSSParser.IdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XCSSParser.ws"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWs([NotNull] XCSSParser.WsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XCSSParser.ws"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWs([NotNull] XCSSParser.WsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
