//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\dev\xcss-parser-csharp\AntlrCSharp\antlr\XCSSParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class XCSSParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OpenBracket=1, CloseBracket=2, OpenParen=3, CloseParen=4, OpenBrace=5, 
		CloseBrace=6, SemiColon=7, Equal=8, Colon=9, Dot=10, Multiply=11, Divide=12, 
		Pipe=13, Underscore=14, Quote=15, DoubleQuote=16, Comment=17, Url=18, 
		Space=19, Cdo=20, Cdc=21, Includes=22, DashMatch=23, Hash=24, Import=25, 
		Page=26, Media=27, Namespace=28, Charset=29, Important=30, Percentage=31, 
		Url_=32, UnicodeRange=33, MediaOnly=34, Not=35, And=36, Dimension=37, 
		UnknownDimension=38, Plus=39, Minus=40, Greater=41, Comma=42, Tilde=43, 
		PseudoNot=44, Number=45, String_=46, PrefixMatch=47, SuffixMatch=48, SubstringMatch=49, 
		FontFace=50, Supports=51, Or=52, Keyframes=53, From=54, To=55, Calc=56, 
		Viewport=57, CounterStyle=58, FontFeatureValues=59, DxImageTransform=60, 
		AtKeyword=61, Variable=62, Var=63, Ident=64, Function_=65, UnexpectedCharacter=66, 
		Name=67;
	public const int
		RULE_parse = 0, RULE_selectorGroup = 1, RULE_selector = 2, RULE_combinator = 3, 
		RULE_simpleSelectorSequence = 4, RULE_elementId = 5, RULE_elementIdValue = 6, 
		RULE_tagName = 7, RULE_typeSelector = 8, RULE_typeNamespacePrefix = 9, 
		RULE_elementName = 10, RULE_universal = 11, RULE_className = 12, RULE_classNameValue = 13, 
		RULE_condition = 14, RULE_subelementSelector = 15, RULE_text = 16, RULE_textValue = 17, 
		RULE_textMatchStyle = 18, RULE_attrib = 19, RULE_attribName = 20, RULE_attribMatchStyle = 21, 
		RULE_attribValue = 22, RULE_pseudo = 23, RULE_functionalPseudo = 24, RULE_expression = 25, 
		RULE_negation = 26, RULE_negationArg = 27, RULE_ident = 28, RULE_ws = 29;
	public static readonly string[] ruleNames = {
		"parse", "selectorGroup", "selector", "combinator", "simpleSelectorSequence", 
		"elementId", "elementIdValue", "tagName", "typeSelector", "typeNamespacePrefix", 
		"elementName", "universal", "className", "classNameValue", "condition", 
		"subelementSelector", "text", "textValue", "textMatchStyle", "attrib", 
		"attribName", "attribMatchStyle", "attribValue", "pseudo", "functionalPseudo", 
		"expression", "negation", "negationArg", "ident", "ws"
	};

	private static readonly string[] _LiteralNames = {
		null, "'['", "']'", "'('", "')'", "'{'", "'}'", "';'", "'='", "':'", "'.'", 
		"'*'", "'/'", "'|'", "'_'", "'''", "'\"'", null, null, null, "'<!--'", 
		"'-->'", "'~='", "'|='", "'#'", null, null, null, null, "'@charset '", 
		null, null, "'url('", null, null, null, null, null, null, "'+'", "'-'", 
		"'>'", "','", "'~'", null, null, null, "'^='", "'$='", "'*='", null, null, 
		null, null, null, null, "'calc('", null, null, null, null, null, null, 
		"'var('"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OpenBracket", "CloseBracket", "OpenParen", "CloseParen", "OpenBrace", 
		"CloseBrace", "SemiColon", "Equal", "Colon", "Dot", "Multiply", "Divide", 
		"Pipe", "Underscore", "Quote", "DoubleQuote", "Comment", "Url", "Space", 
		"Cdo", "Cdc", "Includes", "DashMatch", "Hash", "Import", "Page", "Media", 
		"Namespace", "Charset", "Important", "Percentage", "Url_", "UnicodeRange", 
		"MediaOnly", "Not", "And", "Dimension", "UnknownDimension", "Plus", "Minus", 
		"Greater", "Comma", "Tilde", "PseudoNot", "Number", "String_", "PrefixMatch", 
		"SuffixMatch", "SubstringMatch", "FontFace", "Supports", "Or", "Keyframes", 
		"From", "To", "Calc", "Viewport", "CounterStyle", "FontFeatureValues", 
		"DxImageTransform", "AtKeyword", "Variable", "Var", "Ident", "Function_", 
		"UnexpectedCharacter", "Name"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "XCSSParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static XCSSParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public XCSSParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public XCSSParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ParseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorGroupContext selectorGroup() {
			return GetRuleContext<SelectorGroupContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(XCSSParser.Eof, 0); }
		public ParseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parse; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterParse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitParse(this);
		}
	}

	[RuleVersion(0)]
	public ParseContext parse() {
		ParseContext _localctx = new ParseContext(Context, State);
		EnterRule(_localctx, 0, RULE_parse);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			selectorGroup();
			State = 61;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectorGroupContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext[] selector() {
			return GetRuleContexts<SelectorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector(int i) {
			return GetRuleContext<SelectorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(XCSSParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(XCSSParser.Comma, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext[] ws() {
			return GetRuleContexts<WsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws(int i) {
			return GetRuleContext<WsContext>(i);
		}
		public SelectorGroupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selectorGroup; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterSelectorGroup(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitSelectorGroup(this);
		}
	}

	[RuleVersion(0)]
	public SelectorGroupContext selectorGroup() {
		SelectorGroupContext _localctx = new SelectorGroupContext(Context, State);
		EnterRule(_localctx, 2, RULE_selectorGroup);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			selector();
			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 64;
				Match(Comma);
				State = 65;
				ws();
				State = 66;
				selector();
				}
				}
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SimpleSelectorSequenceContext[] simpleSelectorSequence() {
			return GetRuleContexts<SimpleSelectorSequenceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SimpleSelectorSequenceContext simpleSelectorSequence(int i) {
			return GetRuleContext<SimpleSelectorSequenceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext[] ws() {
			return GetRuleContexts<WsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws(int i) {
			return GetRuleContext<WsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CombinatorContext[] combinator() {
			return GetRuleContexts<CombinatorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CombinatorContext combinator(int i) {
			return GetRuleContext<CombinatorContext>(i);
		}
		public SelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selector; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterSelector(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitSelector(this);
		}
	}

	[RuleVersion(0)]
	public SelectorContext selector() {
		SelectorContext _localctx = new SelectorContext(Context, State);
		EnterRule(_localctx, 4, RULE_selector);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			simpleSelectorSequence();
			State = 74;
			ws();
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Space) | (1L << Plus) | (1L << Greater) | (1L << Tilde))) != 0)) {
				{
				{
				State = 75;
				combinator();
				State = 76;
				simpleSelectorSequence();
				State = 77;
				ws();
				}
				}
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CombinatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus() { return GetToken(XCSSParser.Plus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws() {
			return GetRuleContext<WsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(XCSSParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tilde() { return GetToken(XCSSParser.Tilde, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space() { return GetToken(XCSSParser.Space, 0); }
		public CombinatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_combinator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterCombinator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitCombinator(this);
		}
	}

	[RuleVersion(0)]
	public CombinatorContext combinator() {
		CombinatorContext _localctx = new CombinatorContext(Context, State);
		EnterRule(_localctx, 6, RULE_combinator);
		try {
			State = 92;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Plus:
				EnterOuterAlt(_localctx, 1);
				{
				State = 84;
				Match(Plus);
				State = 85;
				ws();
				}
				break;
			case Greater:
				EnterOuterAlt(_localctx, 2);
				{
				State = 86;
				Match(Greater);
				State = 87;
				ws();
				}
				break;
			case Tilde:
				EnterOuterAlt(_localctx, 3);
				{
				State = 88;
				Match(Tilde);
				State = 89;
				ws();
				}
				break;
			case Space:
				EnterOuterAlt(_localctx, 4);
				{
				State = 90;
				Match(Space);
				State = 91;
				ws();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleSelectorSequenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TagNameContext tagName() {
			return GetRuleContext<TagNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementIdContext[] elementId() {
			return GetRuleContexts<ElementIdContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementIdContext elementId(int i) {
			return GetRuleContext<ElementIdContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassNameContext[] className() {
			return GetRuleContexts<ClassNameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassNameContext className(int i) {
			return GetRuleContext<ClassNameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext[] condition() {
			return GetRuleContexts<ConditionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext condition(int i) {
			return GetRuleContext<ConditionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PseudoContext[] pseudo() {
			return GetRuleContexts<PseudoContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PseudoContext pseudo(int i) {
			return GetRuleContext<PseudoContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NegationContext[] negation() {
			return GetRuleContexts<NegationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NegationContext negation(int i) {
			return GetRuleContext<NegationContext>(i);
		}
		public SimpleSelectorSequenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleSelectorSequence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterSimpleSelectorSequence(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitSimpleSelectorSequence(this);
		}
	}

	[RuleVersion(0)]
	public SimpleSelectorSequenceContext simpleSelectorSequence() {
		SimpleSelectorSequenceContext _localctx = new SimpleSelectorSequenceContext(Context, State);
		EnterRule(_localctx, 8, RULE_simpleSelectorSequence);
		int _la;
		try {
			State = 114;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Multiply:
			case Pipe:
			case MediaOnly:
			case Not:
			case And:
			case Or:
			case From:
			case To:
			case Ident:
				EnterOuterAlt(_localctx, 1);
				{
				State = 94;
				tagName();
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OpenBracket) | (1L << Colon) | (1L << Dot) | (1L << Hash) | (1L << PseudoNot))) != 0)) {
					{
					State = 100;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case Hash:
						{
						State = 95;
						elementId();
						}
						break;
					case Dot:
						{
						State = 96;
						className();
						}
						break;
					case OpenBracket:
						{
						State = 97;
						condition();
						}
						break;
					case Colon:
						{
						State = 98;
						pseudo();
						}
						break;
					case PseudoNot:
						{
						State = 99;
						negation();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					State = 104;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case OpenBracket:
			case Colon:
			case Dot:
			case Hash:
			case PseudoNot:
				EnterOuterAlt(_localctx, 2);
				{
				State = 110;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					State = 110;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case Hash:
						{
						State = 105;
						elementId();
						}
						break;
					case Dot:
						{
						State = 106;
						className();
						}
						break;
					case OpenBracket:
						{
						State = 107;
						condition();
						}
						break;
					case Colon:
						{
						State = 108;
						pseudo();
						}
						break;
					case PseudoNot:
						{
						State = 109;
						negation();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					State = 112;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OpenBracket) | (1L << Colon) | (1L << Dot) | (1L << Hash) | (1L << PseudoNot))) != 0) );
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementIdContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Hash() { return GetToken(XCSSParser.Hash, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ElementIdValueContext elementIdValue() {
			return GetRuleContext<ElementIdValueContext>(0);
		}
		public ElementIdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementId; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterElementId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitElementId(this);
		}
	}

	[RuleVersion(0)]
	public ElementIdContext elementId() {
		ElementIdContext _localctx = new ElementIdContext(Context, State);
		EnterRule(_localctx, 10, RULE_elementId);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			Match(Hash);
			State = 117;
			elementIdValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementIdValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(XCSSParser.Name, 0); }
		public ElementIdValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementIdValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterElementIdValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitElementIdValue(this);
		}
	}

	[RuleVersion(0)]
	public ElementIdValueContext elementIdValue() {
		ElementIdValueContext _localctx = new ElementIdValueContext(Context, State);
		EnterRule(_localctx, 12, RULE_elementIdValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			Match(Name);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TagNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeSelectorContext typeSelector() {
			return GetRuleContext<TypeSelectorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UniversalContext universal() {
			return GetRuleContext<UniversalContext>(0);
		}
		public TagNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tagName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterTagName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitTagName(this);
		}
	}

	[RuleVersion(0)]
	public TagNameContext tagName() {
		TagNameContext _localctx = new TagNameContext(Context, State);
		EnterRule(_localctx, 14, RULE_tagName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				State = 121;
				typeSelector();
				}
				break;
			case 2:
				{
				State = 122;
				universal();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeSelectorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ElementNameContext elementName() {
			return GetRuleContext<ElementNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeNamespacePrefixContext typeNamespacePrefix() {
			return GetRuleContext<TypeNamespacePrefixContext>(0);
		}
		public TypeSelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeSelector; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterTypeSelector(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitTypeSelector(this);
		}
	}

	[RuleVersion(0)]
	public TypeSelectorContext typeSelector() {
		TypeSelectorContext _localctx = new TypeSelectorContext(Context, State);
		EnterRule(_localctx, 16, RULE_typeSelector);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				{
				State = 125;
				typeNamespacePrefix();
				}
				break;
			}
			State = 128;
			elementName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeNamespacePrefixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pipe() { return GetToken(XCSSParser.Pipe, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Multiply() { return GetToken(XCSSParser.Multiply, 0); }
		public TypeNamespacePrefixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeNamespacePrefix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterTypeNamespacePrefix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitTypeNamespacePrefix(this);
		}
	}

	[RuleVersion(0)]
	public TypeNamespacePrefixContext typeNamespacePrefix() {
		TypeNamespacePrefixContext _localctx = new TypeNamespacePrefixContext(Context, State);
		EnterRule(_localctx, 18, RULE_typeNamespacePrefix);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MediaOnly:
			case Not:
			case And:
			case Or:
			case From:
			case To:
			case Ident:
				{
				State = 130;
				ident();
				}
				break;
			case Multiply:
				{
				State = 131;
				Match(Multiply);
				}
				break;
			case Pipe:
				break;
			default:
				break;
			}
			State = 134;
			Match(Pipe);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		public ElementNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterElementName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitElementName(this);
		}
	}

	[RuleVersion(0)]
	public ElementNameContext elementName() {
		ElementNameContext _localctx = new ElementNameContext(Context, State);
		EnterRule(_localctx, 20, RULE_elementName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136;
			ident();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UniversalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Multiply() { return GetToken(XCSSParser.Multiply, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNamespacePrefixContext typeNamespacePrefix() {
			return GetRuleContext<TypeNamespacePrefixContext>(0);
		}
		public UniversalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_universal; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterUniversal(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitUniversal(this);
		}
	}

	[RuleVersion(0)]
	public UniversalContext universal() {
		UniversalContext _localctx = new UniversalContext(Context, State);
		EnterRule(_localctx, 22, RULE_universal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				{
				State = 138;
				typeNamespacePrefix();
				}
				break;
			}
			State = 141;
			Match(Multiply);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(XCSSParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ClassNameValueContext classNameValue() {
			return GetRuleContext<ClassNameValueContext>(0);
		}
		public ClassNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_className; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterClassName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitClassName(this);
		}
	}

	[RuleVersion(0)]
	public ClassNameContext className() {
		ClassNameContext _localctx = new ClassNameContext(Context, State);
		EnterRule(_localctx, 24, RULE_className);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 143;
			Match(Dot);
			State = 144;
			classNameValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassNameValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		public ClassNameValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classNameValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterClassNameValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitClassNameValue(this);
		}
	}

	[RuleVersion(0)]
	public ClassNameValueContext classNameValue() {
		ClassNameValueContext _localctx = new ClassNameValueContext(Context, State);
		EnterRule(_localctx, 26, RULE_classNameValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			ident();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenBracket() { return GetToken(XCSSParser.OpenBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseBracket() { return GetToken(XCSSParser.CloseBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AttribContext attrib() {
			return GetRuleContext<AttribContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubelementSelectorContext subelementSelector() {
			return GetRuleContext<SubelementSelectorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CombinatorContext combinator() {
			return GetRuleContext<CombinatorContext>(0);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterCondition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitCondition(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 28, RULE_condition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			Match(OpenBracket);
			State = 155;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 149;
				attrib();
				}
				break;
			case 2:
				{
				State = 150;
				text();
				}
				break;
			case 3:
				{
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Space) | (1L << Plus) | (1L << Greater) | (1L << Tilde))) != 0)) {
					{
					State = 151;
					combinator();
					}
				}

				State = 154;
				subelementSelector();
				}
				break;
			}
			State = 157;
			Match(CloseBracket);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubelementSelectorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SubelementSelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subelementSelector; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterSubelementSelector(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitSubelementSelector(this);
		}
	}

	[RuleVersion(0)]
	public SubelementSelectorContext subelementSelector() {
		SubelementSelectorContext _localctx = new SubelementSelectorContext(Context, State);
		EnterRule(_localctx, 30, RULE_subelementSelector);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			selector();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextValueContext textValue() {
			return GetRuleContext<TextValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextMatchStyleContext textMatchStyle() {
			return GetRuleContext<TextMatchStyleContext>(0);
		}
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitText(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(Context, State);
		EnterRule(_localctx, 32, RULE_text);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 162;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Tilde) {
				{
				State = 161;
				textMatchStyle();
				}
			}

			State = 164;
			textValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DoubleQuote() { return GetTokens(XCSSParser.DoubleQuote); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DoubleQuote(int i) {
			return GetToken(XCSSParser.DoubleQuote, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Quote() { return GetTokens(XCSSParser.Quote); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Quote(int i) {
			return GetToken(XCSSParser.Quote, i);
		}
		public TextValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterTextValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitTextValue(this);
		}
	}

	[RuleVersion(0)]
	public TextValueContext textValue() {
		TextValueContext _localctx = new TextValueContext(Context, State);
		EnterRule(_localctx, 34, RULE_textValue);
		int _la;
		try {
			State = 182;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DoubleQuote:
				EnterOuterAlt(_localctx, 1);
				{
				State = 166;
				Match(DoubleQuote);
				State = 170;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OpenBracket) | (1L << CloseBracket) | (1L << OpenParen) | (1L << CloseParen) | (1L << OpenBrace) | (1L << CloseBrace) | (1L << SemiColon) | (1L << Equal) | (1L << Colon) | (1L << Dot) | (1L << Multiply) | (1L << Divide) | (1L << Pipe) | (1L << Underscore) | (1L << Quote) | (1L << Comment) | (1L << Url) | (1L << Space) | (1L << Cdo) | (1L << Cdc) | (1L << Includes) | (1L << DashMatch) | (1L << Hash) | (1L << Import) | (1L << Page) | (1L << Media) | (1L << Namespace) | (1L << Charset) | (1L << Important) | (1L << Percentage) | (1L << Url_) | (1L << UnicodeRange) | (1L << MediaOnly) | (1L << Not) | (1L << And) | (1L << Dimension) | (1L << UnknownDimension) | (1L << Plus) | (1L << Minus) | (1L << Greater) | (1L << Comma) | (1L << Tilde) | (1L << PseudoNot) | (1L << Number) | (1L << String_) | (1L << PrefixMatch) | (1L << SuffixMatch) | (1L << SubstringMatch) | (1L << FontFace) | (1L << Supports) | (1L << Or) | (1L << Keyframes) | (1L << From) | (1L << To) | (1L << Calc) | (1L << Viewport) | (1L << CounterStyle) | (1L << FontFeatureValues) | (1L << DxImageTransform) | (1L << AtKeyword) | (1L << Variable) | (1L << Var))) != 0) || ((((_la - 64)) & ~0x3f) == 0 && ((1L << (_la - 64)) & ((1L << (Ident - 64)) | (1L << (Function_ - 64)) | (1L << (UnexpectedCharacter - 64)) | (1L << (Name - 64)))) != 0)) {
					{
					{
					State = 167;
					_la = TokenStream.LA(1);
					if ( _la <= 0 || (_la==DoubleQuote) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					}
					State = 172;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 173;
				Match(DoubleQuote);
				}
				break;
			case Quote:
				EnterOuterAlt(_localctx, 2);
				{
				State = 174;
				Match(Quote);
				State = 178;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OpenBracket) | (1L << CloseBracket) | (1L << OpenParen) | (1L << CloseParen) | (1L << OpenBrace) | (1L << CloseBrace) | (1L << SemiColon) | (1L << Equal) | (1L << Colon) | (1L << Dot) | (1L << Multiply) | (1L << Divide) | (1L << Pipe) | (1L << Underscore) | (1L << DoubleQuote) | (1L << Comment) | (1L << Url) | (1L << Space) | (1L << Cdo) | (1L << Cdc) | (1L << Includes) | (1L << DashMatch) | (1L << Hash) | (1L << Import) | (1L << Page) | (1L << Media) | (1L << Namespace) | (1L << Charset) | (1L << Important) | (1L << Percentage) | (1L << Url_) | (1L << UnicodeRange) | (1L << MediaOnly) | (1L << Not) | (1L << And) | (1L << Dimension) | (1L << UnknownDimension) | (1L << Plus) | (1L << Minus) | (1L << Greater) | (1L << Comma) | (1L << Tilde) | (1L << PseudoNot) | (1L << Number) | (1L << String_) | (1L << PrefixMatch) | (1L << SuffixMatch) | (1L << SubstringMatch) | (1L << FontFace) | (1L << Supports) | (1L << Or) | (1L << Keyframes) | (1L << From) | (1L << To) | (1L << Calc) | (1L << Viewport) | (1L << CounterStyle) | (1L << FontFeatureValues) | (1L << DxImageTransform) | (1L << AtKeyword) | (1L << Variable) | (1L << Var))) != 0) || ((((_la - 64)) & ~0x3f) == 0 && ((1L << (_la - 64)) & ((1L << (Ident - 64)) | (1L << (Function_ - 64)) | (1L << (UnexpectedCharacter - 64)) | (1L << (Name - 64)))) != 0)) {
					{
					{
					State = 175;
					_la = TokenStream.LA(1);
					if ( _la <= 0 || (_la==Quote) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					}
					State = 180;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 181;
				Match(Quote);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextMatchStyleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tilde() { return GetToken(XCSSParser.Tilde, 0); }
		public TextMatchStyleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textMatchStyle; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterTextMatchStyle(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitTextMatchStyle(this);
		}
	}

	[RuleVersion(0)]
	public TextMatchStyleContext textMatchStyle() {
		TextMatchStyleContext _localctx = new TextMatchStyleContext(Context, State);
		EnterRule(_localctx, 36, RULE_textMatchStyle);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(Tilde);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttribContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public WsContext[] ws() {
			return GetRuleContexts<WsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws(int i) {
			return GetRuleContext<WsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttribNameContext attribName() {
			return GetRuleContext<AttribNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttribMatchStyleContext attribMatchStyle() {
			return GetRuleContext<AttribMatchStyleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttribValueContext attribValue() {
			return GetRuleContext<AttribValueContext>(0);
		}
		public AttribContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attrib; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterAttrib(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitAttrib(this);
		}
	}

	[RuleVersion(0)]
	public AttribContext attrib() {
		AttribContext _localctx = new AttribContext(Context, State);
		EnterRule(_localctx, 38, RULE_attrib);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			ws();
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (((((_la - 11)) & ~0x3f) == 0 && ((1L << (_la - 11)) & ((1L << (Multiply - 11)) | (1L << (Pipe - 11)) | (1L << (MediaOnly - 11)) | (1L << (Not - 11)) | (1L << (And - 11)) | (1L << (Or - 11)) | (1L << (From - 11)) | (1L << (To - 11)) | (1L << (Ident - 11)))) != 0)) {
				{
				State = 187;
				attribName();
				}
			}

			State = 190;
			ws();
			State = 196;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Equal) | (1L << Includes) | (1L << DashMatch) | (1L << PrefixMatch) | (1L << SuffixMatch) | (1L << SubstringMatch))) != 0)) {
				{
				State = 191;
				attribMatchStyle();
				State = 192;
				ws();
				State = 193;
				attribValue();
				State = 194;
				ws();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttribNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeNamespacePrefixContext typeNamespacePrefix() {
			return GetRuleContext<TypeNamespacePrefixContext>(0);
		}
		public AttribNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterAttribName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitAttribName(this);
		}
	}

	[RuleVersion(0)]
	public AttribNameContext attribName() {
		AttribNameContext _localctx = new AttribNameContext(Context, State);
		EnterRule(_localctx, 40, RULE_attribName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 199;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
			case 1:
				{
				State = 198;
				typeNamespacePrefix();
				}
				break;
			}
			State = 201;
			ident();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttribMatchStyleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixMatch() { return GetToken(XCSSParser.PrefixMatch, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SuffixMatch() { return GetToken(XCSSParser.SuffixMatch, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SubstringMatch() { return GetToken(XCSSParser.SubstringMatch, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Equal() { return GetToken(XCSSParser.Equal, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Includes() { return GetToken(XCSSParser.Includes, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DashMatch() { return GetToken(XCSSParser.DashMatch, 0); }
		public AttribMatchStyleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribMatchStyle; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterAttribMatchStyle(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitAttribMatchStyle(this);
		}
	}

	[RuleVersion(0)]
	public AttribMatchStyleContext attribMatchStyle() {
		AttribMatchStyleContext _localctx = new AttribMatchStyleContext(Context, State);
		EnterRule(_localctx, 42, RULE_attribMatchStyle);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Equal) | (1L << Includes) | (1L << DashMatch) | (1L << PrefixMatch) | (1L << SuffixMatch) | (1L << SubstringMatch))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttribValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode String_() { return GetToken(XCSSParser.String_, 0); }
		public AttribValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterAttribValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitAttribValue(this);
		}
	}

	[RuleVersion(0)]
	public AttribValueContext attribValue() {
		AttribValueContext _localctx = new AttribValueContext(Context, State);
		EnterRule(_localctx, 44, RULE_attribValue);
		try {
			State = 207;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MediaOnly:
			case Not:
			case And:
			case Or:
			case From:
			case To:
			case Ident:
				EnterOuterAlt(_localctx, 1);
				{
				State = 205;
				ident();
				}
				break;
			case String_:
				EnterOuterAlt(_localctx, 2);
				{
				State = 206;
				Match(String_);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PseudoContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Colon() { return GetTokens(XCSSParser.Colon); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon(int i) {
			return GetToken(XCSSParser.Colon, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionalPseudoContext functionalPseudo() {
			return GetRuleContext<FunctionalPseudoContext>(0);
		}
		public PseudoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pseudo; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterPseudo(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitPseudo(this);
		}
	}

	[RuleVersion(0)]
	public PseudoContext pseudo() {
		PseudoContext _localctx = new PseudoContext(Context, State);
		EnterRule(_localctx, 46, RULE_pseudo);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209;
			Match(Colon);
			State = 211;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Colon) {
				{
				State = 210;
				Match(Colon);
				}
			}

			State = 215;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MediaOnly:
			case Not:
			case And:
			case Or:
			case From:
			case To:
			case Ident:
				{
				State = 213;
				ident();
				}
				break;
			case Function_:
				{
				State = 214;
				functionalPseudo();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionalPseudoContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Function_() { return GetToken(XCSSParser.Function_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws() {
			return GetRuleContext<WsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(XCSSParser.CloseParen, 0); }
		public FunctionalPseudoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionalPseudo; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterFunctionalPseudo(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitFunctionalPseudo(this);
		}
	}

	[RuleVersion(0)]
	public FunctionalPseudoContext functionalPseudo() {
		FunctionalPseudoContext _localctx = new FunctionalPseudoContext(Context, State);
		EnterRule(_localctx, 48, RULE_functionalPseudo);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 217;
			Match(Function_);
			State = 218;
			ws();
			State = 219;
			expression();
			State = 220;
			Match(CloseParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public WsContext[] ws() {
			return GetRuleContexts<WsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws(int i) {
			return GetRuleContext<WsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Plus() { return GetTokens(XCSSParser.Plus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus(int i) {
			return GetToken(XCSSParser.Plus, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Minus() { return GetTokens(XCSSParser.Minus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus(int i) {
			return GetToken(XCSSParser.Minus, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Dimension() { return GetTokens(XCSSParser.Dimension); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dimension(int i) {
			return GetToken(XCSSParser.Dimension, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] UnknownDimension() { return GetTokens(XCSSParser.UnknownDimension); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UnknownDimension(int i) {
			return GetToken(XCSSParser.UnknownDimension, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(XCSSParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(XCSSParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] String_() { return GetTokens(XCSSParser.String_); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode String_(int i) {
			return GetToken(XCSSParser.String_, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext[] ident() {
			return GetRuleContexts<IdentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident(int i) {
			return GetRuleContext<IdentContext>(i);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 50, RULE_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 232;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 229;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Plus:
					{
					State = 222;
					Match(Plus);
					}
					break;
				case Minus:
					{
					State = 223;
					Match(Minus);
					}
					break;
				case Dimension:
					{
					State = 224;
					Match(Dimension);
					}
					break;
				case UnknownDimension:
					{
					State = 225;
					Match(UnknownDimension);
					}
					break;
				case Number:
					{
					State = 226;
					Match(Number);
					}
					break;
				case String_:
					{
					State = 227;
					Match(String_);
					}
					break;
				case MediaOnly:
				case Not:
				case And:
				case Or:
				case From:
				case To:
				case Ident:
					{
					State = 228;
					ident();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 231;
				ws();
				}
				}
				State = 234;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( ((((_la - 34)) & ~0x3f) == 0 && ((1L << (_la - 34)) & ((1L << (MediaOnly - 34)) | (1L << (Not - 34)) | (1L << (And - 34)) | (1L << (Dimension - 34)) | (1L << (UnknownDimension - 34)) | (1L << (Plus - 34)) | (1L << (Minus - 34)) | (1L << (Number - 34)) | (1L << (String_ - 34)) | (1L << (Or - 34)) | (1L << (From - 34)) | (1L << (To - 34)) | (1L << (Ident - 34)))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NegationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PseudoNot() { return GetToken(XCSSParser.PseudoNot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public WsContext[] ws() {
			return GetRuleContexts<WsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public WsContext ws(int i) {
			return GetRuleContext<WsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NegationArgContext negationArg() {
			return GetRuleContext<NegationArgContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(XCSSParser.CloseParen, 0); }
		public NegationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_negation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterNegation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitNegation(this);
		}
	}

	[RuleVersion(0)]
	public NegationContext negation() {
		NegationContext _localctx = new NegationContext(Context, State);
		EnterRule(_localctx, 52, RULE_negation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			Match(PseudoNot);
			State = 237;
			ws();
			State = 238;
			negationArg();
			State = 239;
			ws();
			State = 240;
			Match(CloseParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NegationArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeSelectorContext typeSelector() {
			return GetRuleContext<TypeSelectorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UniversalContext universal() {
			return GetRuleContext<UniversalContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementIdContext elementId() {
			return GetRuleContext<ElementIdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassNameContext className() {
			return GetRuleContext<ClassNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttribContext attrib() {
			return GetRuleContext<AttribContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PseudoContext pseudo() {
			return GetRuleContext<PseudoContext>(0);
		}
		public NegationArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_negationArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterNegationArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitNegationArg(this);
		}
	}

	[RuleVersion(0)]
	public NegationArgContext negationArg() {
		NegationArgContext _localctx = new NegationArgContext(Context, State);
		EnterRule(_localctx, 54, RULE_negationArg);
		try {
			State = 248;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 242;
				typeSelector();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 243;
				universal();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 244;
				elementId();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 245;
				className();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 246;
				attrib();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 247;
				pseudo();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(XCSSParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MediaOnly() { return GetToken(XCSSParser.MediaOnly, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Not() { return GetToken(XCSSParser.Not, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(XCSSParser.And, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Or() { return GetToken(XCSSParser.Or, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode From() { return GetToken(XCSSParser.From, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode To() { return GetToken(XCSSParser.To, 0); }
		public IdentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ident; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterIdent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitIdent(this);
		}
	}

	[RuleVersion(0)]
	public IdentContext ident() {
		IdentContext _localctx = new IdentContext(Context, State);
		EnterRule(_localctx, 56, RULE_ident);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250;
			_la = TokenStream.LA(1);
			if ( !(((((_la - 34)) & ~0x3f) == 0 && ((1L << (_la - 34)) & ((1L << (MediaOnly - 34)) | (1L << (Not - 34)) | (1L << (And - 34)) | (1L << (Or - 34)) | (1L << (From - 34)) | (1L << (To - 34)) | (1L << (Ident - 34)))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comment() { return GetTokens(XCSSParser.Comment); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comment(int i) {
			return GetToken(XCSSParser.Comment, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Space() { return GetTokens(XCSSParser.Space); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space(int i) {
			return GetToken(XCSSParser.Space, i);
		}
		public WsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ws; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.EnterWs(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXCSSParserListener typedListener = listener as IXCSSParserListener;
			if (typedListener != null) typedListener.ExitWs(this);
		}
	}

	[RuleVersion(0)]
	public WsContext ws() {
		WsContext _localctx = new WsContext(Context, State);
		EnterRule(_localctx, 58, RULE_ws);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 255;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 252;
					_la = TokenStream.LA(1);
					if ( !(_la==Comment || _la==Space) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					} 
				}
				State = 257;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x45', '\x105', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 'G', '\n', '\x3', '\f', 
		'\x3', '\xE', '\x3', 'J', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 'R', '\n', 
		'\x4', '\f', '\x4', '\xE', '\x4', 'U', '\v', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x5', '\x5', '_', '\n', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 
		'g', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'j', '\v', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x6', 
		'\x6', 'q', '\n', '\x6', '\r', '\x6', '\xE', '\x6', 'r', '\x5', '\x6', 
		'u', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x5', '\t', '~', '\n', '\t', '\x3', 
		'\n', '\x5', '\n', '\x81', '\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x5', '\v', '\x87', '\n', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x5', '\r', '\x8E', '\n', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x5', '\x10', '\x9B', '\n', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\x9E', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x5', '\x12', '\xA5', '\n', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xAB', 
		'\n', '\x13', '\f', '\x13', '\xE', '\x13', '\xAE', '\v', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xB3', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xB6', '\v', '\x13', '\x3', '\x13', '\x5', 
		'\x13', '\xB9', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x5', '\x15', '\xBF', '\n', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', 
		'\x15', '\xC7', '\n', '\x15', '\x3', '\x16', '\x5', '\x16', '\xCA', '\n', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x5', '\x18', '\xD2', '\n', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\x5', '\x19', '\xD6', '\n', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x5', '\x19', '\xDA', '\n', '\x19', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x5', '\x1B', '\xE8', '\n', '\x1B', '\x3', '\x1B', '\x6', '\x1B', '\xEB', 
		'\n', '\x1B', '\r', '\x1B', '\xE', '\x1B', '\xEC', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x5', '\x1D', '\xFB', '\n', '\x1D', '\x3', '\x1E', '\x3', '\x1E', 
		'\x3', '\x1F', '\a', '\x1F', '\x100', '\n', '\x1F', '\f', '\x1F', '\xE', 
		'\x1F', '\x103', '\v', '\x1F', '\x3', '\x1F', '\x2', '\x2', ' ', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', 
		'\x30', '\x32', '\x34', '\x36', '\x38', ':', '<', '\x2', '\a', '\x3', 
		'\x2', '\x12', '\x12', '\x3', '\x2', '\x11', '\x11', '\x5', '\x2', '\n', 
		'\n', '\x18', '\x19', '\x31', '\x33', '\x6', '\x2', '$', '&', '\x36', 
		'\x36', '\x38', '\x39', '\x42', '\x42', '\x4', '\x2', '\x13', '\x13', 
		'\x15', '\x15', '\x2', '\x115', '\x2', '>', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x41', '\x3', '\x2', '\x2', '\x2', '\x6', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\b', '^', '\x3', '\x2', '\x2', '\x2', '\n', 't', '\x3', '\x2', 
		'\x2', '\x2', '\f', 'v', '\x3', '\x2', '\x2', '\x2', '\xE', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x10', '}', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\x14', '\x86', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x18', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\x91', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x96', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\xA1', '\x3', '\x2', '\x2', '\x2', '\"', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '$', '\xB8', '\x3', '\x2', '\x2', '\x2', '&', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '(', '\xBC', '\x3', '\x2', '\x2', '\x2', '*', '\xC9', 
		'\x3', '\x2', '\x2', '\x2', ',', '\xCD', '\x3', '\x2', '\x2', '\x2', '.', 
		'\xD1', '\x3', '\x2', '\x2', '\x2', '\x30', '\xD3', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\xDB', '\x3', '\x2', '\x2', '\x2', '\x34', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\xEE', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', ':', '\xFC', '\x3', '\x2', '\x2', 
		'\x2', '<', '\x101', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x5', '\x4', 
		'\x3', '\x2', '?', '@', '\a', '\x2', '\x2', '\x3', '@', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x41', 'H', '\x5', '\x6', '\x4', '\x2', '\x42', 
		'\x43', '\a', ',', '\x2', '\x2', '\x43', '\x44', '\x5', '<', '\x1F', '\x2', 
		'\x44', '\x45', '\x5', '\x6', '\x4', '\x2', '\x45', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\x46', '\x42', '\x3', '\x2', '\x2', '\x2', 'G', 'J', '\x3', 
		'\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 'I', 
		'\x3', '\x2', '\x2', '\x2', 'I', '\x5', '\x3', '\x2', '\x2', '\x2', 'J', 
		'H', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\x5', '\n', '\x6', '\x2', 
		'L', 'S', '\x5', '<', '\x1F', '\x2', 'M', 'N', '\x5', '\b', '\x5', '\x2', 
		'N', 'O', '\x5', '\n', '\x6', '\x2', 'O', 'P', '\x5', '<', '\x1F', '\x2', 
		'P', 'R', '\x3', '\x2', '\x2', '\x2', 'Q', 'M', '\x3', '\x2', '\x2', '\x2', 
		'R', 'U', '\x3', '\x2', '\x2', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', '\a', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', ')', '\x2', 
		'\x2', 'W', '_', '\x5', '<', '\x1F', '\x2', 'X', 'Y', '\a', '+', '\x2', 
		'\x2', 'Y', '_', '\x5', '<', '\x1F', '\x2', 'Z', '[', '\a', '-', '\x2', 
		'\x2', '[', '_', '\x5', '<', '\x1F', '\x2', '\\', ']', '\a', '\x15', '\x2', 
		'\x2', ']', '_', '\x5', '<', '\x1F', '\x2', '^', 'V', '\x3', '\x2', '\x2', 
		'\x2', '^', 'X', '\x3', '\x2', '\x2', '\x2', '^', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '^', '\\', '\x3', '\x2', '\x2', '\x2', '_', '\t', '\x3', '\x2', 
		'\x2', '\x2', '`', 'h', '\x5', '\x10', '\t', '\x2', '\x61', 'g', '\x5', 
		'\f', '\a', '\x2', '\x62', 'g', '\x5', '\x1A', '\xE', '\x2', '\x63', 'g', 
		'\x5', '\x1E', '\x10', '\x2', '\x64', 'g', '\x5', '\x30', '\x19', '\x2', 
		'\x65', 'g', '\x5', '\x36', '\x1C', '\x2', '\x66', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '\x66', '\x62', '\x3', '\x2', '\x2', '\x2', '\x66', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x66', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'i', 'u', '\x3', '\x2', '\x2', '\x2', 'j', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'q', '\x5', '\f', '\a', '\x2', 'l', 'q', '\x5', '\x1A', 
		'\xE', '\x2', 'm', 'q', '\x5', '\x1E', '\x10', '\x2', 'n', 'q', '\x5', 
		'\x30', '\x19', '\x2', 'o', 'q', '\x5', '\x36', '\x1C', '\x2', 'p', 'k', 
		'\x3', '\x2', '\x2', '\x2', 'p', 'l', '\x3', '\x2', '\x2', '\x2', 'p', 
		'm', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', '\x2', '\x2', '\x2', 
		'p', 'o', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 
		'r', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 
		's', 'u', '\x3', '\x2', '\x2', '\x2', 't', '`', '\x3', '\x2', '\x2', '\x2', 
		't', 'p', '\x3', '\x2', '\x2', '\x2', 'u', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'w', '\a', '\x1A', '\x2', '\x2', 'w', 'x', '\x5', '\xE', '\b', 
		'\x2', 'x', '\r', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x45', 
		'\x2', '\x2', 'z', '\xF', '\x3', '\x2', '\x2', '\x2', '{', '~', '\x5', 
		'\x12', '\n', '\x2', '|', '~', '\x5', '\x18', '\r', '\x2', '}', '{', '\x3', 
		'\x2', '\x2', '\x2', '}', '|', '\x3', '\x2', '\x2', '\x2', '~', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', '\x5', '\x14', '\v', '\x2', 
		'\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', 
		'\x5', '\x16', '\f', '\x2', '\x83', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x84', '\x87', '\x5', ':', '\x1E', '\x2', '\x85', '\x87', '\a', '\r', 
		'\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x88', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '\xF', 
		'\x2', '\x2', '\x89', '\x15', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', 
		'\x5', ':', '\x1E', '\x2', '\x8B', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'\x8C', '\x8E', '\x5', '\x14', '\v', '\x2', '\x8D', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\a', '\r', '\x2', '\x2', 
		'\x90', '\x19', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', '\f', 
		'\x2', '\x2', '\x92', '\x93', '\x5', '\x1C', '\xF', '\x2', '\x93', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x5', ':', '\x1E', '\x2', 
		'\x95', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x96', '\x9D', '\a', '\x3', 
		'\x2', '\x2', '\x97', '\x9E', '\x5', '(', '\x15', '\x2', '\x98', '\x9E', 
		'\x5', '\"', '\x12', '\x2', '\x99', '\x9B', '\x5', '\b', '\x5', '\x2', 
		'\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9E', 
		'\x5', ' ', '\x11', '\x2', '\x9D', '\x97', '\x3', '\x2', '\x2', '\x2', 
		'\x9D', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', 
		'\a', '\x4', '\x2', '\x2', '\xA0', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\x5', '\x6', '\x4', '\x2', '\xA2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA5', '\x5', '&', '\x14', '\x2', '\xA4', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x5', '$', 
		'\x13', '\x2', '\xA7', '#', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAC', 
		'\a', '\x12', '\x2', '\x2', '\xA9', '\xAB', '\n', '\x2', '\x2', '\x2', 
		'\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAE', '\x3', '\x2', 
		'\x2', '\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', 
		'\x3', '\x2', '\x2', '\x2', '\xAD', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB9', '\a', '\x12', 
		'\x2', '\x2', '\xB0', '\xB4', '\a', '\x11', '\x2', '\x2', '\xB1', '\xB3', 
		'\n', '\x3', '\x2', '\x2', '\xB2', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\xB3', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', 
		'\xB7', '\xB9', '\a', '\x11', '\x2', '\x2', '\xB8', '\xA8', '\x3', '\x2', 
		'\x2', '\x2', '\xB8', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB9', '%', 
		'\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\a', '-', '\x2', '\x2', '\xBB', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBE', '\x5', '<', '\x1F', 
		'\x2', '\xBD', '\xBF', '\x5', '*', '\x16', '\x2', '\xBE', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC6', '\x5', '<', '\x1F', 
		'\x2', '\xC1', '\xC2', '\x5', ',', '\x17', '\x2', '\xC2', '\xC3', '\x5', 
		'<', '\x1F', '\x2', '\xC3', '\xC4', '\x5', '.', '\x18', '\x2', '\xC4', 
		'\xC5', '\x5', '<', '\x1F', '\x2', '\xC5', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', ')', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xCA', '\x5', '\x14', '\v', '\x2', '\xC9', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\x5', ':', '\x1E', '\x2', '\xCC', 
		'+', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\t', '\x4', '\x2', '\x2', 
		'\xCE', '-', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD2', '\x5', ':', '\x1E', 
		'\x2', '\xD0', '\xD2', '\a', '\x30', '\x2', '\x2', '\xD1', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD5', '\a', '\v', '\x2', '\x2', 
		'\xD4', '\xD6', '\a', '\v', '\x2', '\x2', '\xD5', '\xD4', '\x3', '\x2', 
		'\x2', '\x2', '\xD5', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD9', 
		'\x3', '\x2', '\x2', '\x2', '\xD7', '\xDA', '\x5', ':', '\x1E', '\x2', 
		'\xD8', '\xDA', '\x5', '\x32', '\x1A', '\x2', '\xD9', '\xD7', '\x3', '\x2', 
		'\x2', '\x2', '\xD9', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xDA', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\xDB', '\xDC', '\a', '\x43', '\x2', '\x2', 
		'\xDC', '\xDD', '\x5', '<', '\x1F', '\x2', '\xDD', '\xDE', '\x5', '\x34', 
		'\x1B', '\x2', '\xDE', '\xDF', '\a', '\x6', '\x2', '\x2', '\xDF', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\xE0', '\xE8', '\a', ')', '\x2', '\x2', '\xE1', 
		'\xE8', '\a', '*', '\x2', '\x2', '\xE2', '\xE8', '\a', '\'', '\x2', '\x2', 
		'\xE3', '\xE8', '\a', '(', '\x2', '\x2', '\xE4', '\xE8', '\a', '/', '\x2', 
		'\x2', '\xE5', '\xE8', '\a', '\x30', '\x2', '\x2', '\xE6', '\xE8', '\x5', 
		':', '\x1E', '\x2', '\xE7', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE7', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\xE7', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE7', 
		'\xE6', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', 
		'\x2', '\xE9', '\xEB', '\x5', '<', '\x1F', '\x2', '\xEA', '\xE7', '\x3', 
		'\x2', '\x2', '\x2', '\xEB', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\x3', '\x2', '\x2', 
		'\x2', '\xED', '\x35', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEF', '\a', 
		'.', '\x2', '\x2', '\xEF', '\xF0', '\x5', '<', '\x1F', '\x2', '\xF0', 
		'\xF1', '\x5', '\x38', '\x1D', '\x2', '\xF1', '\xF2', '\x5', '<', '\x1F', 
		'\x2', '\xF2', '\xF3', '\a', '\x6', '\x2', '\x2', '\xF3', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\xF4', '\xFB', '\x5', '\x12', '\n', '\x2', '\xF5', 
		'\xFB', '\x5', '\x18', '\r', '\x2', '\xF6', '\xFB', '\x5', '\f', '\a', 
		'\x2', '\xF7', '\xFB', '\x5', '\x1A', '\xE', '\x2', '\xF8', '\xFB', '\x5', 
		'(', '\x15', '\x2', '\xF9', '\xFB', '\x5', '\x30', '\x19', '\x2', '\xFA', 
		'\xF4', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xF5', '\x3', '\x2', '\x2', 
		'\x2', '\xFA', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xF7', '\x3', 
		'\x2', '\x2', '\x2', '\xFA', '\xF8', '\x3', '\x2', '\x2', '\x2', '\xFA', 
		'\xF9', '\x3', '\x2', '\x2', '\x2', '\xFB', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\xFC', '\xFD', '\t', '\x5', '\x2', '\x2', '\xFD', ';', '\x3', 
		'\x2', '\x2', '\x2', '\xFE', '\x100', '\t', '\x6', '\x2', '\x2', '\xFF', 
		'\xFE', '\x3', '\x2', '\x2', '\x2', '\x100', '\x103', '\x3', '\x2', '\x2', 
		'\x2', '\x101', '\xFF', '\x3', '\x2', '\x2', '\x2', '\x101', '\x102', 
		'\x3', '\x2', '\x2', '\x2', '\x102', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x103', '\x101', '\x3', '\x2', '\x2', '\x2', '\x1E', 'H', 'S', '^', '\x66', 
		'h', 'p', 'r', 't', '}', '\x80', '\x86', '\x8D', '\x9A', '\x9D', '\xA4', 
		'\xAC', '\xB4', '\xB8', '\xBE', '\xC6', '\xC9', '\xD1', '\xD5', '\xD9', 
		'\xE7', '\xEC', '\xFA', '\x101',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
