//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\dev\xcss-parser-csharp\AntlrCSharp\XCSSParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XCSSParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IXCSSParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.stylesheet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStylesheet([NotNull] XCSSParser.StylesheetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>goodCharset</c>
	/// labeled alternative in <see cref="XCSSParser.charset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodCharset([NotNull] XCSSParser.GoodCharsetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>badCharset</c>
	/// labeled alternative in <see cref="XCSSParser.charset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadCharset([NotNull] XCSSParser.BadCharsetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>goodImport</c>
	/// labeled alternative in <see cref="XCSSParser.imports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodImport([NotNull] XCSSParser.GoodImportContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>badImport</c>
	/// labeled alternative in <see cref="XCSSParser.imports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadImport([NotNull] XCSSParser.BadImportContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>goodNamespace</c>
	/// labeled alternative in <see cref="XCSSParser.namespace_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodNamespace([NotNull] XCSSParser.GoodNamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>badNamespace</c>
	/// labeled alternative in <see cref="XCSSParser.namespace_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadNamespace([NotNull] XCSSParser.BadNamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.namespacePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacePrefix([NotNull] XCSSParser.NamespacePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.media"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMedia([NotNull] XCSSParser.MediaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.mediaQueryList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMediaQueryList([NotNull] XCSSParser.MediaQueryListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.mediaQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMediaQuery([NotNull] XCSSParser.MediaQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.mediaType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMediaType([NotNull] XCSSParser.MediaTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.mediaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMediaExpression([NotNull] XCSSParser.MediaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.mediaFeature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMediaFeature([NotNull] XCSSParser.MediaFeatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.page"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPage([NotNull] XCSSParser.PageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.pseudoPage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudoPage([NotNull] XCSSParser.PseudoPageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.selectorGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectorGroup([NotNull] XCSSParser.SelectorGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] XCSSParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.combinator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCombinator([NotNull] XCSSParser.CombinatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.simpleSelectorSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleSelectorSequence([NotNull] XCSSParser.SimpleSelectorSequenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.typeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSelector([NotNull] XCSSParser.TypeSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.typeNamespacePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeNamespacePrefix([NotNull] XCSSParser.TypeNamespacePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.elementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementName([NotNull] XCSSParser.ElementNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.universal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniversal([NotNull] XCSSParser.UniversalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] XCSSParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrib([NotNull] XCSSParser.AttribContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.pseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudo([NotNull] XCSSParser.PseudoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.functionalPseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionalPseudo([NotNull] XCSSParser.FunctionalPseudoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] XCSSParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegation([NotNull] XCSSParser.NegationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.negationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegationArg([NotNull] XCSSParser.NegationArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>goodOperator</c>
	/// labeled alternative in <see cref="XCSSParser.operator_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodOperator([NotNull] XCSSParser.GoodOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>badOperator</c>
	/// labeled alternative in <see cref="XCSSParser.operator_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadOperator([NotNull] XCSSParser.BadOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>goodProperty</c>
	/// labeled alternative in <see cref="XCSSParser.property_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodProperty([NotNull] XCSSParser.GoodPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>badProperty</c>
	/// labeled alternative in <see cref="XCSSParser.property_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadProperty([NotNull] XCSSParser.BadPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>knownRuleset</c>
	/// labeled alternative in <see cref="XCSSParser.ruleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnownRuleset([NotNull] XCSSParser.KnownRulesetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unknownRuleset</c>
	/// labeled alternative in <see cref="XCSSParser.ruleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownRuleset([NotNull] XCSSParser.UnknownRulesetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationList([NotNull] XCSSParser.DeclarationListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>knownDeclaration</c>
	/// labeled alternative in <see cref="XCSSParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnownDeclaration([NotNull] XCSSParser.KnownDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unknownDeclaration</c>
	/// labeled alternative in <see cref="XCSSParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownDeclaration([NotNull] XCSSParser.UnknownDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.prio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrio([NotNull] XCSSParser.PrioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] XCSSParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] XCSSParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>knownTerm</c>
	/// labeled alternative in <see cref="XCSSParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnownTerm([NotNull] XCSSParser.KnownTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unknownTerm</c>
	/// labeled alternative in <see cref="XCSSParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownTerm([NotNull] XCSSParser.UnknownTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>badTerm</c>
	/// labeled alternative in <see cref="XCSSParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadTerm([NotNull] XCSSParser.BadTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.function_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_([NotNull] XCSSParser.Function_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.dxImageTransform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDxImageTransform([NotNull] XCSSParser.DxImageTransformContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.hexcolor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexcolor([NotNull] XCSSParser.HexcolorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] XCSSParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.percentage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPercentage([NotNull] XCSSParser.PercentageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimension([NotNull] XCSSParser.DimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.unknownDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownDimension([NotNull] XCSSParser.UnknownDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.any_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_([NotNull] XCSSParser.Any_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unknownAtRule</c>
	/// labeled alternative in <see cref="XCSSParser.atRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownAtRule([NotNull] XCSSParser.UnknownAtRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.unused"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnused([NotNull] XCSSParser.UnusedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] XCSSParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.nestedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedStatement([NotNull] XCSSParser.NestedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.groupRuleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupRuleBody([NotNull] XCSSParser.GroupRuleBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsRule([NotNull] XCSSParser.SupportsRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsCondition([NotNull] XCSSParser.SupportsConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsConditionInParens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsConditionInParens([NotNull] XCSSParser.SupportsConditionInParensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsNegation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsNegation([NotNull] XCSSParser.SupportsNegationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsConjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsConjunction([NotNull] XCSSParser.SupportsConjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsDisjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsDisjunction([NotNull] XCSSParser.SupportsDisjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.supportsDeclarationCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupportsDeclarationCondition([NotNull] XCSSParser.SupportsDeclarationConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.generalEnclosed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralEnclosed([NotNull] XCSSParser.GeneralEnclosedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.url"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUrl([NotNull] XCSSParser.UrlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.var_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_([NotNull] XCSSParser.Var_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.calc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalc([NotNull] XCSSParser.CalcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.calcSum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcSum([NotNull] XCSSParser.CalcSumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.calcProduct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcProduct([NotNull] XCSSParser.CalcProductContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.calcValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcValue([NotNull] XCSSParser.CalcValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.fontFaceRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFontFaceRule([NotNull] XCSSParser.FontFaceRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>knownFontFaceDeclaration</c>
	/// labeled alternative in <see cref="XCSSParser.fontFaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnownFontFaceDeclaration([NotNull] XCSSParser.KnownFontFaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unknownFontFaceDeclaration</c>
	/// labeled alternative in <see cref="XCSSParser.fontFaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownFontFaceDeclaration([NotNull] XCSSParser.UnknownFontFaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.keyframesRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyframesRule([NotNull] XCSSParser.KeyframesRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.keyframeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyframeBlock([NotNull] XCSSParser.KeyframeBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.keyframeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyframeSelector([NotNull] XCSSParser.KeyframeSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.viewport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitViewport([NotNull] XCSSParser.ViewportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.counterStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCounterStyle([NotNull] XCSSParser.CounterStyleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.fontFeatureValuesRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFontFeatureValuesRule([NotNull] XCSSParser.FontFeatureValuesRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.fontFamilyNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFontFamilyNameList([NotNull] XCSSParser.FontFamilyNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.fontFamilyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFontFamilyName([NotNull] XCSSParser.FontFamilyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.featureValueBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeatureValueBlock([NotNull] XCSSParser.FeatureValueBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.featureType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeatureType([NotNull] XCSSParser.FeatureTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.featureValueDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeatureValueDefinition([NotNull] XCSSParser.FeatureValueDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdent([NotNull] XCSSParser.IdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XCSSParser.ws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWs([NotNull] XCSSParser.WsContext context);
}
